# Generated by Django 4.2.16 on 2024-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_schedule', models.CharField(max_length=200)),
                ('second_schedule', models.EmailField(max_length=200)),
                ('third_schedule', models.CharField(max_length=200)),
                ('fourth_schedule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
    ]
