# Generated by Django 4.2.16 on 2024-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=240)),
                ('group', models.CharField(max_length=200)),
                ('authority', models.CharField(max_length=200)),
            ],
        ),
    ]
