# Generated by Django 4.2.16 on 2024-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
