# Generated by Django 4.2.16 on 2024-10-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_user_email_alter_user_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='連絡事項'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fast_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AM①'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fourth_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PM②'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='second_schedule',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='AM②'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='third_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PM①'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='班'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=200, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='電話番号'),
        ),
    ]
