# Generated by Django 4.2.16 on 2024-10-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authority',
        ),
    ]
