# Generated by Django 4.2.16 on 2024-10-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_category_schedulename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timehour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_hour', models.CharField(max_length=200, verbose_name='時')),
            ],
        ),
        migrations.CreateModel(
            name='Timeminutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.CharField(max_length=200, verbose_name='分')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='schedulename',
            name='schedule_name',
            field=models.CharField(max_length=200, verbose_name='予定区分'),
        ),
    ]
