# Generated by Django 4.2.16 on 2024-10-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_schedule_category_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
