# Generated by Django 4.2.16 on 2024-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='calendar_day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='idnumber',
            field=models.CharField(default=1, max_length=200, verbose_name='社員番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='氏名'),
            preserve_default=False,
        ),
    ]
