# Generated by Django 4.2.16 on 2024-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_schedule_calendar_day_schedule_idnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='calendar_day',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
