# Generated by Django 4.2.16 on 2024-10-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alter_schedule_fast_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fast_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.schedulename', verbose_name='AM1'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fourth_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PM2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='second_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AM2'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='third_schedule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PM1'),
        ),
    ]
