# Generated by Django 4.2.16 on 2024-10-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_remove_schedule_fast_schedule_schedule_fast_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fast_schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='fast_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.schedulename', verbose_name='AM1'),
        ),
    ]
