# Generated by Django 4.2.16 on 2024-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_remove_schedule_fast_schedule_schedule_fast_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='calendar_day',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
