# Generated by Django 4.2.16 on 2024-10-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_alter_schedule_calendar_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fast_schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='fast_schedule',
            field=models.ManyToManyField(blank=True, to='crud.schedulename', verbose_name='AM1'),
        ),
    ]
