# Generated by Django 4.2.16 on 2024-10-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_remove_schedule_fast_schedule_schedule_fast_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='fast_schedule',
            new_name='first_schedule',
        ),
    ]
