# Generated by Django 4.2.16 on 2024-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_alter_schedule_first_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='first_schedule',
            field=models.CharField(blank=True, choices=[('千代田区', '千代田区'), ('中央区', '中央区'), ('港区', '港区'), ('品川区', '品川区'), ('大田区', '大田区'), ('会議・打合せ', '会議・打合せ'), ('研修', '研修'), ('出張', '出張'), ('在宅', '在宅'), ('休暇', '休暇'), ('明休', '明休'), ('代休', '代休')], max_length=10, null=True, verbose_name='AM1'),
        ),
    ]
