# Generated by Django 4.2.16 on 2024-10-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_alter_schedule_fourth_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='idnumber',
            field=models.CharField(max_length=7, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=7, verbose_name='社員番号'),
        ),
    ]
