# Generated by Django 4.2.16 on 2024-10-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_alter_schedule_idnumber_alter_user_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=7, unique=True, verbose_name='社員番号'),
        ),
    ]
