# Generated by Django 4.2.16 on 2024-10-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_alter_user_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=7, verbose_name='社員番号'),
        ),
    ]
