# Generated by Django 4.2.16 on 2024-10-20 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0026_schedule_name_alter_user_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='idnumber',
            field=models.CharField(max_length=200, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=200, verbose_name='社員番号'),
        ),
    ]
