# Generated by Django 4.2.16 on 2024-10-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_alter_schedule_idnumber_alter_schedule_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
