# Generated by Django 4.2.16 on 2024-10-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_remove_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='idnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.user', to_field='idnumber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(max_length=200, unique=True, verbose_name='社員番号'),
        ),
    ]
